// Generated by `npm run bindings` from Rust. Do not edit.

export type AutomaticPolicy = { schemaVersion: number, content: UpdateMode, project: UpdateMode, instances: Array<InstanceUpdateMode>, };

export type AutomaticReport = { instanceId: string, checkedAt: number, updates: Array<ContentUpdate>, status: string, project: ProjectUpdate | null, };

export type InstanceUpdateMode = { id: string, content: UpdateMode | null, project: UpdateMode | null, };

export type UpdateMode = "off" | "check" | "install";

export type FilePolicy = "REQUIRED_LOCKED" | "OPTIONAL" | "USER_ALLOWED" | "USER_FORBIDDEN";

export type ProjectFile = { path: string, sha256: string, sha512: string, size: number, source: string | null, policy: FilePolicy, group: string | null, };

export type ProjectManifest = { schemaVersion: number, id: string, version: string, name: string, minecraft: string, loader: Loader, loaderVersion: string | null, creatorStudio: boolean, forbidExternalMods: boolean, files: Array<ProjectFile>, optionalGroups: Array<string>, launch: ProjectLaunch, packSource: PackSource | null, };

export type ProjectLaunch = { memoryMib: number | null, };

export type PackSource = { projectId: string, versionId: string, };

export type StudioRequest = { id: string, name: string, version: string, forbidExternalMods: boolean, policies: Array<StudioFilePolicy>, };

export type StudioFilePolicy = { path: string, policy: FilePolicy, group: string | null, };

export type ProjectView = { manifest: ProjectManifest | null, packSource: PackSource | null, localSource: string | null, };

export type ProjectUpdate = { current: string, available: string | null, versionId: string | null, status: string, };

export type ProjectPlan = { token: string, instanceId: string, action: string, current: string, available: string, changes: Array<string>, warnings: Array<string>, optionalGroups: Array<string>, selectedGroups: Array<string>, };

export type PackPreview = { token: string, source: string, name: string, version: string, description: string, minecraft: string, loader: Loader, loaderVersion: string | null, requiredFiles: number, optionalFiles: Array<string>, downloadBytes: number, embeddedBytes: number, warnings: Array<string>, };

export type PackJob = { name: string, phase: string, instanceId: string | null, completedFiles: number, totalFiles: number, downloadedBytes: number, totalBytes: number, error: CommandError | null, };

export type PackExport = { fileName: string, referencedFiles: number, embeddedFiles: number, omitted: Array<string>, };

export type PackExportRequest = { id: string, includeWorlds: boolean, includeLocal: boolean, };

export type ExternalCandidate = { key: string, name: string, minecraft: string, loader: Loader, loaderVersion: string | null, source: string, warnings: Array<string>, };

export type CatalogQuery = { query: string, kind: string, minecraft: string, loader: string, category: string, environment: string, sort: string, offset: number, instanceId: string | null, };

export type CatalogPage = { hits: Array<ContentHit>, nextOffset: number | null, total: number, cached: boolean, };

export type ContentHit = { iconUrl: string | null, id: string, title: string, description: string, author: string, kind: string, downloads: number, categories: Array<string>, };

export type ContentCategory = { name: string, project_type: string, };

export type ContentLoader = { name: string, supported_project_types: Array<string>, };

export type ContentTags = { categories: Array<ContentCategory>, loaders: Array<ContentLoader>, gameVersions: Array<string>, };

export type ContentLicense = { id: string, name: string, };

export type ContentProject = { icon_url: string | null, id: string, title: string, description: string, body: string, project_type: string, license: ContentLicense, client_side: string, server_side: string, environment: Array<string>, };

export type ContentDependency = { version_id: string | null, project_id: string | null, file_name: string | null, dependency_type: string, };

export type ContentHashes = { sha1: string, sha512: string, };

export type ContentFile = { id: string | null, filename: string, url: string, hashes: ContentHashes, size: number, primary: boolean, file_type: string | null, };

export type ContentVersion = { id: string, project_id: string, name: string, version_number: string, version_type: string, date_published: string, status: string, game_versions: Array<string>, loaders: Array<string>, environment: string, dependencies: Array<ContentDependency>, files: Array<ContentFile>, };

export type ContentDetails = { project: ContentProject, versions: Array<ContentVersion>, compatibleInstances: Array<string>, };

export type ContentRequest = { instanceId: string, projectId: string, versionId: string, };

export type ContentCreateRequest = { projectId: string, versionId: string, instance: CreateInstance, };

export type ContentRecord = { local?: LocalMetadata | null, iconUrl: string | null, provider: string, projectId: string, title: string, kind: string, version: ContentVersion, file: ContentFile, directory: string, dependency: boolean, };

export type ContentAdoptionRequest = { instanceId: string, directory: string, filename: string, recognize: boolean, };

export type ContentAdoptionPlan = { diagnostics: ModDiagnostics, plan: ContentPlan, warnings: Array<string>, metadata: LocalMetadata, };

export type ContentPlan = { newInstance: CreateInstance | null, token: string, instanceId: string, files: Array<ContentRecord>, optionalDependencies: number, alreadyInstalled: number, totalBytes: number, };

export type ContentJob = { instanceId: string, phase: string, completedFiles: number, totalFiles: number, downloadedBytes: number, totalBytes: number, currentFile: string | null, error: CommandError | null, };

export type InstalledContent = { record: ContentRecord, status: string, };

export type UntrackedContent = { manageable: boolean, directory: string, filename: string, kind: string, title: string, version: string, metadata: LocalMetadata | null, status: string, disabled: boolean, };

export type ContentAction = "enable" | "disable" | "delete";

export type ContentSelection = { directory: string, filename: string, sha512: string, };

export type ContentChange = { instanceId: string, action: ContentAction, files: Array<ContentSelection>, };

export type ContentHistory = { id: string, timestamp: number, action: string, titles: Array<string>, };

export type LocalMetadata = { versions: Array<LocalModVersion>, dependencies: Array<LocalDependency>, modIds: Array<string>, loader: string, minecraft: Array<string>, required: Array<string>, warnings: Array<string>, };

export type LocalModVersion = { id: string, version: string | null, alias: boolean, };

export type LocalDependency = { ownerId: string, id: string, relation: string, ranges: Array<string>, dialect: string, };

export type DependencyTarget = { title: string, version: string | null, directory: string, filename: string, enabled: boolean, };

export type DependencyCheck = { dependency: LocalDependency, status: string, severity: string, targets: Array<DependencyTarget>, };

export type ModDiagnostic = { title: string, directory: string, filename: string, enabled: boolean, status: string, warnings: Array<string>, checks: Array<DependencyCheck>, };

export type ModDiagnostics = { complete: boolean, errors: number, warnings: number, mods: Array<ModDiagnostic>, };

export type LocalContentPlan = { diagnostics: ModDiagnostics, plan: ContentPlan, warnings: Array<string>, };

export type WorldImport = { id: string, title: string, source: string, sha512: string, importedAt: number, };

export type ContentWorld = { id: string, title: string, imported: WorldImport | null, };

export type WorldArchiveRequest = { instanceId: string, source: string, kind: string, world: string | null, title: string, };

export type WorldArchivePlan = { token: string, instanceId: string, kind: string, title: string, world: string, source: string, bytes: number, files: number, warnings: Array<string>, };

export type WorldProjectRequest = { instanceId: string, projectId: string, versionId: string, world: string, };

export type LocalDependencyPlan = { plan: ContentPlan, parents: Array<ContentRecord>, };

export type ContentUpdatePolicy = { projectId: string, pinned: boolean, ignoredVersion: string | null, };

export type ContentUpdate = { projectId: string, title: string, currentVersion: string, status: string, candidate: ContentVersion | null, policy: ContentUpdatePolicy, };

export type ContentUpdateRequest = { instanceId: string, files: Array<ContentSelection>, };

export type ContentUpdatePlan = { plan: ContentPlan, previous: Array<ContentRecord>, };

export type ContentRestorePoint = { id: string, timestamp: number, title: string, files: number, available: boolean, settingsAvailable: boolean, projectPoint: boolean, };

export type Locale = "ru-RU" | "en-US";

export type Motion = "system" | "reduced";

export type Settings = { schemaVersion: number, locale: Locale, motion: Motion, uiScale: number, versionVisibility: VersionVisibility, customJavaPath: string | null, localNickname: string, nicknameSkins: boolean, downloadConcurrency: number, cacheLimitMb: number, };

export type SettingsSnapshot = { values: Settings, revision: number, };

export type SaveSettingsRequest = { values: Settings, expectedRevision: number, };

export type AppInfo = { name: string, version: string, platform: string, databaseSchema: number, dataDirectory: string, };

export type Bootstrap = { info: AppInfo, settings: SettingsSnapshot, profiles: ProfileSnapshot, };

export type ErrorCode = "RATE_LIMITED" | "CONTENT_INCOMPATIBLE" | "CONTENT_UNSUPPORTED" | "CONTENT_CONFLICT" | "DEPENDENCY_CONFLICT" | "STORAGE_UNAVAILABLE" | "DATA_CORRUPT" | "SCHEMA_TOO_NEW" | "INVALID_SETTINGS" | "SETTINGS_CONFLICT" | "WORKER_UNAVAILABLE" | "INVALID_INPUT" | "NOT_FOUND" | "RECORD_CONFLICT" | "UNSAFE_PATH" | "LIBRARY_BUSY" | "SOURCE_CHANGED" | "OPEN_FOLDER_FAILED" | "NETWORK" | "INTEGRITY" | "UNSAFE_ARCHIVE" | "CANCELLED" | "UNSUPPORTED_VERSION" | "JAVA_UNAVAILABLE" | "INSTANCE_BUSY" | "LAUNCH_FAILED";

export type CommandError = { code: ErrorCode, retryable: boolean, };

export type Loader = "vanilla" | "fabric" | "forge" | "neo_forge";

export type InstanceType = "vanilla" | "fabric" | "forge" | "neo_forge" | "managed_project" | "creator_studio";

export type InstallStatus = "not_installed" | "installed";

export type AutoMode = "auto";

export type Instance = { schemaVersion: number, id: string, revision: number, name: string, minecraftVersion: string, loader: Loader, loaderVersion: string | null, instanceType: InstanceType, collectionId: string | null, status: InstallStatus, javaMode: AutoMode, memoryMode: AutoMode, lastAccountId: string | null, createdAt: number, updatedAt: number, lastPlayedAt: number | null, favorite: boolean, iconSource: IconSource, managedShortcut: ManagedShortcut | null, iconRef: string | null, coverRef: string | null, providerRefs: Array<string>, installedContentIds: Array<string>, };

export type Accent = "sage" | "amber" | "rose" | "teal" | "slate";

export type CollectionIcon = "folder" | "leaf" | "camera" | "users" | "archive" | "flask";

export type Collection = { schemaVersion: number, id: string, revision: number, name: string, description: string, accent: Accent, icon: CollectionIcon, order: number, coverRef: string | null, };

export type LibrarySnapshot = { instances: Array<Instance>, collections: Array<Collection>, };

export type LibraryChange = { snapshot: LibrarySnapshot, affectedId: string, preservedDirectory: string | null, };

export type CreateInstance = { name: string, minecraftVersion: string, loader: Loader, collectionId: string | null, };

export type UpdateInstance = { id: string, expectedRevision: number, name: string, collectionId: string | null, };

export type DuplicateInstance = { id: string, expectedRevision: number, name: string, };

export type DeleteMode = "preserve_worlds" | "everything";

export type DeleteInstance = { id: string, expectedRevision: number, mode: DeleteMode, };

export type SaveCollection = { id: string | null, expectedRevision: number | null, name: string, description: string, accent: Accent, icon: CollectionIcon, };

export type RecordRequest = { id: string, expectedRevision: number, };

export type InstanceLogo = { id: string, name: string, image: string, };

export type AppUpdate = { version: string, notes: string, size: number | null, };

export type InstanceSummary = { enabledMods: number, disabledMods: number, directoryBytes: number | null, };

export type FolderTarget = "data" | "instance" | "mods" | "logs" | "backup";

export type OpenFolder = { target: FolderTarget, id: string | null, };

export type VersionKind = "release" | "snapshot" | "old_beta" | "old_alpha" | "other";

export type GameVersion = { id: string, kind: VersionKind, releasedAt: string, };

export type VersionCatalog = { versions: Array<GameVersion>, latestRelease: string, latestSnapshot: string, cached: boolean, };

export type JavaRuntime = { executable: string, major: number, version: string, architecture: string, managed: boolean, };

export type GameAction = "install" | "local";

export type GameRequest = { id: string, action: GameAction, };

export type JobPhase = "interrupted" | "resolving" | "java" | "loader" | "downloading" | "extracting" | "verifying" | "launching" | "completed" | "cancelled" | "failed";

export type GameJob = { action: GameAction, paused: boolean, cachedFiles: number, repairedFiles: number, retries: number, totalBytes: number, verifiedBytes: number, bytesPerSecond: number, etaSeconds: number | null, activeFiles: Array<TransferFile>, instanceId: string, phase: JobPhase, completedFiles: number, totalFiles: number, downloadedBytes: number, error: CommandError | null, };

export type TransferFile = { index: number, name: string, received: number, total: number, };

export type CacheStats = { disposableBytes: number, partialBytes: number, files: number, };

export type GameSession = { instanceId: string, running: boolean, exitCode: number | null, logPath: string, };

export type GameState = { job: GameJob | null, sessions: Array<GameSession>, };

export type VersionVisibility = { releases: boolean, snapshots: boolean, beta: boolean, alpha: boolean, other: boolean, };

export type IconSource = "automatic" | "builtin" | "custom";

export type ManagedShortcut = { fileName: string, iconRevision: number, };

export type ShortcutPlan = { instanceId: string, arguments: Array<string>, available: boolean, };

export type SetFavorite = { id: string, expectedRevision: number, favorite: boolean, };

export type LocalProfile = { id: string, nickname: string, offlineUuid: string, };

export type ProfileSnapshot = { profiles: Array<LocalProfile>, activeProfileId: string, revision: number, };

export type ProfileAction = "create" | "rename" | "delete" | "select";

export type EditProfile = { action: ProfileAction, id: string | null, nickname: string | null, expectedRevision: number, };

export type SkinStatus = "found" | "missing" | "unavailable" | "cached";

export type SkinView = { status: SkinStatus, png: string | null, slim: boolean, fetchedAt: number, };

export type ConfigureLaunch = { id: string, expectedRevision: number, loaderVersion: string | null, };

export type LoaderVersion = { id: string, stable: boolean, };

export type LoaderCatalog = { versions: Array<LoaderVersion>, cached: boolean, };
